### ISSUE TITLE
Use Monarch

### ISSUE THREAD

**Issue by HaxxonHax** [HaxxonHax/the-inn#5]
How can we extend Monarch to use this?  Monarch has play hooks, so we should to utilize the play hooks for playing the main cards.

**Comment by HaxxonHax** [comment]
Is Monarch tablet-friendly?

**Comment by HaxxonHax** [comment]
When trying to use Monarch:
```
foundry.js:316 TypeError: Cannot read properties of null (reading 'data')
[Detected 1 package: monarch]
    at Card.get back [as back] (foundry.js:13854:29)
    at Card.get backImg [as backImg] (foundry.js:13874:17)
    at MonarchCardsConfig.js:11:28
    at Array.map (<anonymous>)
    at MonarchPile.getData (MonarchCardsConfig.js:8:30)
    at async MonarchPile._render (foundry.js:3062:18)
    at async MonarchPile._render (foundry.js:3764:5)
    at async MonarchPile._render (MonarchApplicationMixin.js:86:3)
```
